# -*- coding: utf-8 -*-
"""
Created on Sun Sep  3 23:36:44 2017

@author: Ziya
This code snippet counts the number of bases each base category has
"""
#Provide your DNA string below
string = 'ACCGACTCCAAACGGTAACCATCTCGTCTACATCGCAAATTTTAAGCGTTATTCTCTGCTGACGGGGTAAGTCCTCAGTGCAGCAATCTTGAGGGTAAATTCATCGAAGGTCCGTACGATGGCACTCGCTGGCTGCACTACAAGGCTATCTGAGTGCGGTATCGGCCCAAGTGCTATTCAGTGACGTTCGCGCCCGGGGCGGGAAATTTACTCAGCGCAATCCCAGAAGCTTCCCGCGGTCTGACCTGCAAGTCGGCCTGCCTTGAGCATATGGAAAGGGTACTATCTCATGAATCACAGAGAACGTAAGCAGATGTCTTAAAGTAACATAGCTCGATGGTGATAACCCAGCATCAAAAATCGACCACGGACCGTCCGTAAGTCTTAGTTAATTGTAGGAATGCGCTAGGCTTCACTCAGCACCACGCGTTTAATAAAGCCAATGTAAATTTCCAGTAAGACGAGGAAAATCACCAAGGATGTTAGGCGTCCTCCTTACTCCTCTACCTGTTTGCGATGATGTTAGTGCAGTGGACGTCCTTGAAACGTGCCCCGGGTTTGGTAGACAACCCGTACTCGTTCGTGGAGTGCTCAGTGTAGTTTTTATTCGCACTTGAAAGTGTTACTACTATCCTCTGGTGCCTTGGTTCGTTGTGACGTATCTAGGGCCTAGGCACGAGATGCTGGTGCAAATTTTGGGATAGTGAAAGCGTGAGCGCACCTTCATGAGGGACCTGGGAAGTTCTCTTGTCTGGGAACACACGTTCCTGAACGTGCTTGCAAACCTGGCGCGAGATACTAATGCCCCTGATCTTCGCTTACGGACGGGGTTTCGCTCAGAGGCTAAGGGGCGAGCCTCCCTGCCAGCTCCGATGTCGGTGGCGCTATAGATCGCGATTTAGAGCGGGTTCT'
counts = [0,0,0,0]

for base in string:
    if base == 'A':
        counts[0] += 1
    if base == 'C':
        counts[1] += 1
    if base == 'G':
        counts[2] += 1
    if base == 'T':
        counts[3] += 1
print(counts)
