# -*- coding: utf-8 -*-
"""
Created on Tue Sep  5 15:23:20 2017

@author: ASUS
This code snippet calculates the number of possible RNA sequence of an aminoacid sequence
"""

#This dictionary defines how many possible RNA equivalent each aminoacid has
protein_to_possible_rna_dict = {'F':2,'L':6,'S':6,'Y':2,'C':2,'W':1,'P':4,'H':2,'Q':2,'R':6,'I':3,'M':1,'T':4,'N':2,'K':2,'V':4,'A':4,'D':2,'E':2,'G':4}
stop_codons = ['UAA','UGA','UGA']
number_of_stop_codons = 3

aa_sequence = 'MQYAAWFYGVRIWQEGCFPWVYGPMATPGRCPGVQTQRGLWFRQQWANRASIRTDMFGDDAWDFCFNLKLSEWRHRCELYHWDMLCNFKGDAVGFIQCPKSMVHKINWVQRPMVVVNKTMNHGTNNCPLDTFICEQIRFEIFPSVSPCMTILWNNLKYDMNAVSHESSPRQWISMVVEWMIRAAKWKPWCHMFCNHNNWNYTCCATPTNPFQFDYYIYAKICGCCPWWQSKKWQIIADWEVMQNDYDNYCQQMFRDHNQVFWVQIYSMYQDHYKNWPNLDNYGMDFYAYAKLYLHRKVKWYPTHAFYMHPLKEMPNMPSPVNYEYQTYQHPACKREPHQRQSLHAGQHEFMNDLRSFRQAKVNHPDNETRRAEMPCNINTMRWFKGMECGIAGYYPQITFMMWDIELLVRTKAWWHYRYRFFAQFGECLHPEIASMRFEQMVIDLLGSPDAWNWNYLKYIMKFQRVYQRFQLMATCRWSINNLCDCPENGALFMAWQEFMEHDDWWDSIDEEHRKYSRVTHESFCAHTISHARDDWYQDRFGPQYRVTKIDTFIYRFKACQPYPKSSEWLIVMWDVWSDSPNVEDPHCKRMHPRDRIEGNVNPVKTVHWLIIYYVHNHNVNYIYQRLIVKVWMMIQILKLYIDATNCSDWRWNSGYRWWVADTVYKVNRCPHGFEGSQVHTFGSCNNVGNSCMAYDGRWQYNWKPCPIIQECPDMQFSWHVTLGTWLQWPLNDQNGVFQAFMWERKCNAIECKTWMLFRSEFLICQKAYVHDEQDCFRSINGKWKMHICKASCDIQVAMCDWGLQAKFQFGYACQKNCEKHTKKGEKHNRCDQQSLNVYGTSGYWQALDRHMDLPVQCCFFERGPYDRHFYVVCYEEYWKRMHCRTYEWAIVLCFRQTMSQGVRTPIWEGRDHVICFQSWVQGWPCVNPGLPCVMNNIFQIGETEEWFDPQHEFNKVIHVKRNVRDYLYESSIFLKEWLQKWNPTGQKFQVRMLLMM'

#Assuming input is provided properly
possibility_amount = 1
for aa in aa_sequence:
    possibility_amount = (possibility_amount * protein_to_rna_possibily_dict[aa]) % 1E6

#Number of stop codons is taken into account. 
#Despite being not explicity defined in the sequence they exist
possibility_amount = (possibility_amount * number_of_stop_codons)

print(possibility_amount)
    
