# -*- coding: utf-8 -*-
"""
Created on Sun Sep  3 23:45:39 2017

@author: ASUS
This code snippet takes the complement and reverse of a DNA string
"""

string = 'GTGGTTACGCTCCCGGGGGGGTTCTACGTGCAGATACTGTTCGGGAAGAAGGAGGCACGTCAGGGAGCGCACCCCCCGGTCTACTTGACGGTGGTGAACGTTATCGGCTGGGCCATGTCGTGGAGATAGGAAGCAGGGGAAGTGTGTAAGACAAGTGTACGTGTGTGCATATCTTTTCGTTTGTATAATGTATCGCCAGTGTTATGTCAACCCTAATCCCGGGTATTAAGGAGACAGTCGTGGATTCAGAGGGGTGTCGTCGTGAGCTAGGGGACATTCTTGTAGCGGAGATATGACAACGAGACCGTTGAACATCTTAGTTTTAAGTCTCGCCTCACCTTCCTGGCAAGCTAAACCGGTGGTTCAGCGGTGTTTTGCCCACTTAACCGCCCACCGATTAAGCCATCGACCTACCGAGGTCGGATATAGTGGACCATAGTTACCAAGAATCACCTCAGGTCTGGGCTCATGAAAGGATTAAGGGGTATACAAAAGGCACACAGCCCATCTTACGTTGATCGAGGCGGATGGTTTAAAGGTCCCAGCTTACCTTTTTCCCTTAGACGTAGACTACCGTCGAGGGAGCTGAGAGATTTCAGCCGTATTAAACAACTGAAACCGTCCAACGATACTCATATTCTACGGTGCTCAAGGTGACCGCTGACGGTGATTCTTGACCCCCCTCACTATAGAACACCTCCTATCGCACGACACATTGTCGACTTTTGACCACCCCCGGTTCCCGGGTTTACCTAGAGATCTAGGAATCACTCAAATCGTCTCTCGTGGCGGTGTGCAATGCCAAGAAGAGAAACACTACGGTCGACGAGGGGGCCTGTTATTCTAGGGACGGTCGTGCAACTGCTCCGC'

#Take the reverse
reversed_string = string[::-1]

#Take the compelement of the reverse
complement_reversed_string = ""
for base in reversed_string:
    if(base == 'A'):
        complement_reversed_string += 'T'
    if(base == 'C'):
        complement_reversed_string += 'G'
    if(base == 'G'):
        complement_reversed_string += 'C'
    if(base == 'T'):
        complement_reversed_string += 'A'
print(complement_reversed_string)
