# -*- coding: utf-8 -*-
"""
Created on Sun Sep  3 23:45:39 2017

@author: ASUS
This code snippet takes the complement and reverse of a DNA string
"""

string = 'GTGGTTACGCTCCCGGGGGGGTTCTACGTGCAGATACTGTTCGGGAAGAAGGAGGCACGTCAGGGAGCGCACCCCCCGGTCTACTTGACGGTGGTGAACGTTATCGGCTGGGCCATGTCGTGGAGATAGGAAGCAGGGGAAGTGTGTAAGACAAGTGTACGTGTGTGCATATCTTTTCGTTTGTATAATGTATCGCCAGTGTTATGTCAACCCTAATCCCGGGTATTAAGGAGACAGTCGTGGATTCAGAGGGGTGTCGTCGTGAGCTAGGGGACATTCTTGTAGCGGAGATATGACAACGAGACCGTTGAACATCTTAGTTTTAAGTCTCGCCTCACCTTCCTGGCAAGCTAAACCGGTGGTTCAGCGGTGTTTTGCCCACTTAACCGCCCACCGATTAAGCCATCGACCTACCGAGGTCGGATATAGTGGACCATAGTTACCAAGAATCACCTCAGGTCTGGGCTCATGAAAGGATTAAGGGGTATACAAAAGGCACACAGCCCATCTTACGTTGATCGAGGCGGATGGTTTAAAGGTCCCAGCTTACCTTTTTCCCTTAGACGTAGACTACCGTCGAGGGAGCTGAGAGATTTCAGCCGTATTAAACAACTGAAACCGTCCAACGATACTCATATTCTACGGTGCTCAAGGTGACCGCTGACGGTGATTCTTGACCCCCCTCACTATAGAACACCTCCTATCGCACGACACATTGTCGACTTTTGACCACCCCCGGTTCCCGGGTTTACCTAGAGATCTAGGAATCACTCAAATCGTCTCTCGTGGCGGTGTGCAATGCCAAGAAGAGAAACACTACGGTCGACGAGGGGGCCTGTTATTCTAGGGACGGTCGTGCAACTGCTCCGC'

#Take the reverse
reversed_string = string[::-1]

#Create a dictionary
complement_dict = {'A':'T','T':'A','G':'C','C':'G'}

#Take the compelement of the reverse
complement_reversed_string = ""
for base in reversed_string:
    complement_reversed_string += complement_dict[base]
print(complement_reversed_string)
